### ISSUE TITLE
>I am a FOSS developer that has random interests in various software fields.

### ISSUE THREAD

**Issue by SDRausty** [agnostic-apollo/agnostic-apollo#1]
>I am a FOSS developer that has random interests in various software fields.

![Screenshot_20220327-090931](https://user-images.githubusercontent.com/27742457/160284034-839385e7-001b-4d2a-a3e7-db68688bd7f4.png)

@agnostic-apollo a FOSS developer!  How so via deleting years of worldwide applauded open source contributions?

**Comment by SDRausty** [comment]
Closing paths for users and missguiding them is your goal after watching your hideous effect on the open source community for almost a year.  Leave open souce now!

**Comment by SDRausty** [comment]
>I am a FOSS developer that has random interests in various software fields.

NO! You axe, block and pervert open source.  You should remove yourself from open source asap.

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and misguiding Android Termux open source  Android Termux users is one of your goals @agnostic-apollo after watching your hideous effect at the open source community for almost a year now and your behavior is ill/sick;  Leave open source now!  Go BACK into your crib!

**Comment by SDRausty** [comment]
>I am a FOSS developer that has random interests in various software fields.

![Screenshot_20220327-083813](https://user-images.githubusercontent.com/27742457/160284086-bbd3b2c0-3874-465c-9ee3-05e5e4929abe.png)

**Comment by SDRausty** [comment]
>have @fornwall's account

A perverted developer and thief is what u seem 2be @agnostic-apollo!

**Comment by SDRausty** [comment]
I will pray for u lovely.

**Comment by SDRausty** [comment]
![Screenshot_20220326-222042](https://user-images.githubusercontent.com/27742457/160284902-a66b734d-4447-474e-950b-da148ac72ea6.png)

I will pray for u lovely.

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u, ur victims & those to be...

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u @grimler91, ur victims [Malmo stabbing prompts soul-searching in Sweden](https://www.bbc.com/news/world-europe-60867754) proffesor 2be & those to be...

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u @grimler91, ur victims [Malmo stabbing prompts soul-searching in Sweden](https://www.bbc.com/news/world-europe-60867754) PHD proffesor 2be & those to be...

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u @grimler91, ur victims such as  [Malmo stabbing prompts soul-searching in Sweden](https://www.bbc.com/news/world-europe-60867754) and thise who could NOT speak PHD proffesor 2be & those to be...

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u @grimler91, ur victims such as  [Malmo stabbing prompts soul-searching in Sweden](https://www.bbc.com/news/world-europe-60867754) and those who could NOT speak because of their trauma that you prey on PHD proffesor 2be & those to be...

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u @grimler91, ur victims such as  [Malmo stabbing prompts soul-searching in Sweden](https://www.bbc.com/news/world-europe-60867754) and those who could NOT speak because of their trauma that you seem to be preying on PHD proffesor 2be & those to be...

**Comment by SDRausty** [comment]
If you manage 2crack @fornwall's GitHub account, will you delete his work, or modify it like u already av?

**Comment by SDRausty** [comment]
stay silent turd

**Comment by SDRausty** [comment]
go back into ur hole period

**Comment by SDRausty** [comment]
n stay der

**Comment by SDRausty** [comment]
untill u mature trud

**Comment by SDRausty** [comment]
dry n turn into dust

**Comment by SDRausty** [comment]
grabber @agnostic-apollo

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and grimler91 after watching your hideous effect at the open source community for almost a year now (more than five year @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your hole!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and grimler91 after watching your hideous effect at the open source community for almost a year now (more than five year @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your dirty holes!  And stay there untill u av learned!

**Comment by SDRausty** [comment]
pray 4learning about us

**Comment by SDRausty** [comment]
n pray 4learning about us if u can

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur missguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your dirty holes!  And stay there untill u av learned!

**Comment by SDRausty** [comment]
n pray 4learning about us all, if u can

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur missguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your dirty holes!  And stay there untill u av learned!

**Comment by SDRausty** [comment]
>A perverted developer and thief is what u seem 2be.

@grimler91 ditto +Ateacher; explains sweden school tragedy!  I pray 4u @grimler91 n ur victims such as  [Malmo stabbing prompts soul-searching in Sweden](https://www.bbc.com/news/world-europe-60867754) victims and those who could NOT speak because of their trauma that you seem to be preying upon in order to have a written thesis, dictator PHD proffesor 2be.

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your crib holes!  And stay untill u av learned 2pray 4Worldwide peace!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your crib holes!  And stay untill u av learned 2pray 4Worldwide peace n open source!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your crib holes!  And stay untill u av learned 2pray 4Worldwide peace wid open source Nsim!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and Android Termux misguiding open source  Android Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your crib holes!  And please stay there until u av learned 2pray 4Worldwide peace wid open source and open source hardware/software!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and misguiding Android open source Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous effect at the open source community for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your crib holes!  And please stay there until u av learned 2pray 4Worldwide peace wid open source and open source hardware/software!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and misguiding Android open source Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous terrible effect upon the open source community and our World for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul]);  Leave open source now!  Go BACK into your crib holes!  And please stay there until u av learned 2pray 4Worldwide peace wid open source and open source hardware/software!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and misguiding Android open source Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous and terrible effect upon the open source community and our World for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul](https://www.bbc.com/news/world-europe-60867754);  Leave open source now!  Go BACK into your crib holes!  And please stay there until u av learned 2pray 4Worldwide peace wid open source and open source hardware/software!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and misguiding Android open source Termux users is one of your goals @agnostic-apollo and @grimler91 after watching your hideous and terrible effect upon the open source community and our World for almost a year now (more than five years of ur misguidance @grimler91 [now ur work = malmo school soul](https://www.bbc.com/news/world-europe-60867754));  Leave open source now!  Go BACK into your crib holes!  And please stay there until u av learned 2pray 4Worldwide peace wid open source and open source hardware/software!

**Comment by SDRausty** [comment]
Closing paths for open source Termux users and misguiding Android open source Termux users is one of your goals @agnostic-apollo and @grimler91's too after watching your hideous and terrible effect upon the open source community and our World for almost a year now (more than five years of observing @grimler91's intentional misguidance for profit, and [now ur work = malmo school soul searching](https://www.bbc.com/news/world-europe-60867754));  Leave open source now!  Go BACK into your cribs!  And please stay there until u av learned 2pray 4Worldwide peace wid open source and open source hardware/software!

**Comment by SDRausty** [comment]
You'll 'r schooled into fewer!

We want more!

**Comment by SDRausty** [comment]
You all 'r schooled into fewer!

We want more!

**Comment by SDRausty** [comment]
You all'r schooled into fewer!

We want more!

**Comment by SDRausty** [comment]
You all'r schooled into fewer!  Twelve Earth years +diplomas n more, if u wanna!

We all want more!

**Comment by SDRausty** [comment]
You all'r schooled into fewer!  Twelve Earth years +diplomas n more, if u wanna!

We all want more!  Not less of da good suff that seems to be working in our palms (hold SER emitting smartphones very close 2U, were day hot?)!

**Comment by SDRausty** [comment]
term

**Comment by SDRausty** [comment]
9

**Comment by SDRausty** [comment]
term sig 9 px

**Comment by SDRausty** [comment]
px; term sig 9

**Comment by SDRausty** [comment]
[px](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L216&&#L218); term sig 9

**Comment by SDRausty** [comment]
>have @fornwall's account

A perverted developer and thief is what u seem 2be @agnostic-apollo!

**Comment by SDRausty** [comment]
Malware by @agnostic-apollo and @grimler91 report forthcoming n I'm laughing!

**Comment by SDRausty** [comment]
i know how 2delete n pervert 2

do I

look

**Comment by SDRausty** [comment]
Do i ask u to see?

LEARN BASH HACKER

LEARN CODING HACKER

Any idiot can break things cracker!  Learn wad our forebearers desired, please!

**Comment by SDRausty** [comment]
idiot with authority = dictator = putin = @agnostic-apollo = @grimler91 wih is PHD 2be = sims

**Comment by SDRausty** [comment]
Swedish soul searching answer:

idiot with authority = dictator = putin = @agnostic-apollo = @grimler91 wih their PHD 2be = sims

**Comment by SDRausty** [comment]
delete authority? question

Do you have delete authority https://github.com/termux ?

**Comment by SDRausty** [comment]
delete authority? question

Your account @agnostic-apollo seems to be deleting very usefull information worldwide @agnostic-apollo; Are u proud of ur work @agnostic-apollo?

Do you have delete authority @agnostic-apollo at https://github.com/termux?

**Comment by SDRausty** [comment]
[Swedish soul searching](https://www.bbc.com/news/world-europe-60867754) (>"string of violent attacks at schools in Sweden") answer:

idiot with authority = dictator = putin (too much button playing) = @agnostic-apollo = @grimler91 wid their PHDs 2be = &sims schooled into our teachers at school

**Comment by SDRausty** [comment]
grabn thingz

**Comment by SDRausty** [comment]
Are you being paid by closed source @agnostic-apollo?

**Comment by SDRausty** [comment]
>I am not well versed in the gradle and android sdk/apk build systems, so some issues will need more research

reference https://github.com/termux/termux-packages/pull/7227#issuecomment-893022283

![Screenshot_20220326-222042](https://user-images.githubusercontent.com/27742457/160284902-a66b734d-4447-474e-950b-da148ac72ea6.png)

Closing paths for Termux users and misguiding users while not being well versed in topics seems to be one of your goals @agnostic-apollo!  After watching your hideous effect at the open source community for almost a year now;  Leave open source now!  Go BACK into your crib and learn before mangling published and applauded worldwide works!

**Comment by SDRausty** [comment]
>I am a FOSS developer that has random interests in various software fields.

![Screenshot_20220327-083813](https://user-images.githubusercontent.com/27742457/160284086-bbd3b2c0-3874-465c-9ee3-05e5e4929abe.png)

>have @fornwall's account

Why did you request @fornwall's account when you are not well versed in the gradle and android sdk/apk build systems?

**Comment by agnostic-apollo** [comment]
>How so via deleting years of worldwide applauded open source contributions?

I wasn't even a reddit moderator at the time for when you posted that reddit removed post screenshot.

>Why did you request @fornwall's account when you are not well versed in the gradle and android sdk/apk build systems?

Please read the comment again for why. Termux team needs access to fornwall's playstore account so that we can unpublish apps, so that new users don't install apps with privilege escalation vulnerabilities that would put them at risk. Check https://termux.github.io/general/2022/02/15/termux-apps-vulnerability-disclosures.html

One doesn't need knowledge of gradle and apk build systems to unpublish apps on playstore, dumbass...

I see that you still are continuing to spam the @termux devs instead of apologizing and improving your behaviour. I guess babies like you throwing tantrums is why there is a 3+ years age limit on termux.

![termux-age-limit](https://user-images.githubusercontent.com/31106828/161115578-7fefc07e-3c66-4d07-ab50-075c02028991.jpg)

**Comment by SDRausty** [comment]
bueno/buena

**Comment by ghost** [comment]
@agnostic-apollo A *genious* joke about Termux age targeting, I almost *died* laughing. So you guys bully your contributors, delay issue resolving for ages, and when it boils down to an answer, you just make jokes and everybody laughs, so your useless project is saved. Termux is undeveloped for years, it should have been rewritten like 200 times already.

**Comment by ghost** [comment]
@agnostic-apollo Also, good luck trying to hack a Google account, as it is an impossible task to perform.

**Comment by agnostic-apollo** [comment]
@yakovlevegor (relatively new user with only `TermuxArch` forked), you should check https://github.com/termux/termux-packages/issues/202#issuecomment-1072972799 for why he was banned. He was violating our `Explicitly toxic behavior, trolling and flood are not tolerated` [community policy](https://wiki.termux.com/wiki/Community). If you join a community, you are supposed to follow its policy or leave or be banned. He was tolerated many times before ban instead of on first offense. If I was doing something similar on some other org's repo, I would definitely expect a ban. Do you think he pulled this kind of shit in linux repos, they would have just let it go and let him spam them repeatedly in multiple repos? Linus would probably have dissed him pretty hard (and I would have loved to see that).

His termux wiki entries were removed because we can't officially recommend someone pulling that kind of spamming on our repos. He could also have retaliated in his repos with potential malicious intent against our users. If users want to use his repos, they are free to do so at their own risk. But we have no obligation to recommend them even if they as claimed as "worldwide applauded". Moreover, `openjdk` and `gradle` are how are you supposed to be compiling apps as per official way, that's how android studio does it too internally, so other methods are not necessary to be recommended anyways, specially non-official third party ones.

>, delay issue resolving for ages

You are more than welcome to send pull requests with actual good solutions as per our coding guidelines. We don't owe anybody anything and definitely not expedited resolution of issues. The active termux maintainers are doing work for free (beer) since as far as I know, they are all getting `~$0` in donations. If you want expedited resolution of something, put a reasonable bounty on it.

>so your useless project is saved. 

If it's useless, you don't have to use it or be involved.

>Termux is undeveloped for years, it should have been rewritten like 200 times already.

If a dev is rewriting an app 200 times in 7 years, they would likely be considered a pretty bad dev who has no sense of coding design or maintenance. But you are welcome to fork and rewrite a gazillion times, as long as you comply with our licenses.

> Also, good luck trying to hack a Google account, as it is an impossible task to perform.

Google would be considered one of the best in terms of security but saying its impossible to hack googles means you don't under the state of software security. It may be hard, but not impossible.

Anyways, I am done wasting time on this.

**Comment by ghost** [comment]
> @yakovlevegor (relatively new user with only `TermuxArch` forked), you should check [termux/termux-packages#202 (comment)](https://github.com/termux/termux-packages/issues/202#issuecomment-1072972799) for why he was banned. He was violating our `Explicitly toxic behavior, trolling and flood are not tolerated` [community policy](https://wiki.termux.com/wiki/Community). If you join a community, you are supposed to follow its policy or leave or be banned. He was tolerated many times before ban instead of on first offense. If I was doing something similar on some other org's repo, I would definitely expect a ban. Do you think he pulled this kind of shit in linux repos, they would have just let it go and let him spam them repeatedly in multiple repos? Linus would probably have dissed him pretty hard (and I would have loved to see that).
> 
> His termux wiki entries were removed because we can't officially recommend someone pulling that kind of spamming on our repos. He could also have retaliated in his repos with potential malicious intent against our users. If users want to use his repos, they are free to do so at their own risk. But we have no obligation to recommend them even if they as claimed as "worldwide applauded". Moreover, `openjdk` and `gradle` are how are you supposed to be compiling apps as per official way, that's how android studio does it too internally, so other methods are not necessary to be recommended anyways, specially non-official third party ones.
> 
> > , delay issue resolving for ages
> 
> You are more than welcome to send pull requests with actual good solutions as per our coding guidelines. We don't owe anybody anything and definitely not expedited resolution of issues. The active termux maintainers are doing work for free (beer) since as far as I know, they are all getting `~$0` in donations. If you want expedited resolution of something, put a reasonable bounty on it.
> 
> > so your useless project is saved.
> 
> If it's useless, you don't have to use it or be involved.
> 
> > Termux is undeveloped for years, it should have been rewritten like 200 times already.
> 
> If a dev is rewriting an app 200 times in 7 years, they would likely be considered a pretty bad dev who has no sense of coding design or maintenance. But you are welcome to fork and rewrite a gazillion times, as long as you comply with our licenses.
> 
> > Also, good luck trying to hack a Google account, as it is an impossible task to perform.
> 
> Google would be considered one of the best in terms of security but saying its impossible to hack googles means you don't under the state of software security. It may be hard, but not impossible.
> 
> Anyways, I am done wasting time on this.

Yadda, yadda. Tldr, for making it personal. SDRausty does great stuff, you discredit that stuff and ban him. I've read that discussion where you openly bully him and hide his comments and contributions in your repository, anybody would go insane if he contributed that much and received none of attention.
